WebgentleBookStore/Models/BookModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebgentleBookStore.Models
{
    public class BookModel
    {

        public int Id { get; set; }
        [StringLength (100,MinimumLength =5)]
        [Required (ErrorMessage = "Please enter the title of your book")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Please enter the author of your book")]
        public string Author { get; set; }
         [StringLength(100, MinimumLength = 5)]
        [Required(ErrorMessage = "Please enter the error ")] 
        public string Description { get; set; }

        public string Category { get; set; }
        [Required(ErrorMessage = "Please choose the language of your book")]
        public int LanguageId { get; set; }
        [Required(ErrorMessage = "Please enter the total pages")]
        [Display(Name ="Total Number of Pages")]
        public int? TotalPages { get; set; }
       
    }
}

WebgentleBookStore/Models/CarModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebgentleBookStore.Models
{
    public class CarModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }

        public double Price { get; set; }
        public double Millage { get; set; }
    }
}

WebgentleBookStore/Models/LanguageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebgentleBookStore.Models
{
    public class LanguageModel
    {
        public int  Id { get; set; }
          public string Text { get; set; }
    }
}

WebgentleBookStore/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.Design;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebgentleBookStore.Models;
using WebgentleBookStore.Repository;

namespace WebgentleBookStore.Controllers
{
    public class BookController : Controller
    {
        private readonly BookRepository _bookRepository = null;
        [ViewData]
        public string Title { get; set; }

        //Or also for complex types
        [ViewData]
        public BookModel Book { get; set; }
        public BookController(BookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }
        public async Task<IActionResult> GetAllBooks()
        {

            var data = await _bookRepository.GetAllBooks();
            return View(data);
        }

        [Route("book-details/{id}", Name = "bookDetailsRoute")]
        public async Task<IActionResult> GetBook(int id)
        {

            var data = await _bookRepository.GetBookById(id);
            return View(data);
        }
        public List<BookModel> SearchBooks(string bookName, string authorName)
        {
            return _bookRepository.SearchBook(bookName, authorName);
        }


        public ViewResult AddNewBook(bool isSuccess = false, int bookId = 0)
        {
            ViewBag.Language = new List<string>() { "English", "Hindi", "Ducth" };
            ViewBag.Lang = new SelectList(GetLanguages(), "Id", "Text");
            ViewBag.IsSuccess = isSuccess;
            ViewBag.BookId = bookId;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddNewBook(BookModel bookModel)
        {
            if (ModelState.IsValid)
            {
                int id = await _bookRepository.AddNewBook(bookModel);
                if (id > 0)
                {
                    return RedirectToAction(nameof(AddNewBook), new { isSuccess = true, bookId = id });
                }


            }
            ViewBag.Language = new List<string>() { "English", "Hindi", "Ducth" };
            ViewBag.Lang = new SelectList(GetLanguages(), "Id","Text");
            ViewBag.IsSuccess = false;
            ViewBag.BookId = 0;


            ModelState.AddModelError("", "There is an error");
            ModelState.AddModelError("", "There is an error second One");
            return View();
        }

        private List<LanguageModel> GetLanguages(){

            return new List<LanguageModel>() {
                    new LanguageModel (){Id=1, Text="Hindu"},
                     new LanguageModel (){Id=2, Text="English"},
                      new LanguageModel (){Id=3, Text="Ducth"},

            };
        
        }
    }
}

WebgentleBookStore/Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebgentleBookStore.Models;
using WebgentleBookStore.Repository;

namespace WebgentleBookStore.Controllers
{
    public class CarController : Controller
    {
        private readonly CarRespositroy _carRespositroy = null;
        public CarController(CarRespositroy carRespositroy)
        {
            _carRespositroy = carRespositroy;

        }
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult AddCar(bool isSuccess = false, int carId = 0)
        {
            ViewBag.isSuccess = isSuccess;
            ViewBag.carId = carId; 
            return View();
        }

        [HttpPost]
        public IActionResult AddCar(CarModel carModel)
        {
           int id =  _carRespositroy.AddNewCar(carModel);
            if (id > 0)
            {
                return RedirectToAction(nameof(AddCar),new { isSuccess = true, carId = id });
            }
            return View();
        }
    }
}

WebgentleBookStore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Dynamic;
using WebgentleBookStore.Models;

namespace WebgentleBookStore.Controllers
{
    public class HomeController : Controller
    {
        [ViewData]
        public string CustomProperty { get; set; }
        [ViewData]
        public string Title { get; set; }
        public ViewResult Index()
        {
            // return View("AboutUs");
            //Full path needs the .cshtml extension
            // return View("~/TempView/yomiView.cshtml");
            //relative path does not need the .cshtml extension
            //return View("../../TempView/yomiView");
            ViewBag.Title = "Book Lab";
            dynamic data = new ExpandoObject();
            data.Id = 23;
            data.Name = "ABABYOMI";
            ViewBag.Data = data;

            ViewData["data"] = new BookModel() { Author = "askksks", Language = "kksks" };
            Title = "Home";
            CustomProperty = "Custom Value";  
            return View();
    }
    public ViewResult AboutUs()
    {
            Title = "About Us";
        return View();
    }
    public ViewResult ContactUs()
    {
            Title = "Contact Us";
        return View();
    }
}
}

WebgentleBookStore/Views/Book/AddNewBook.cshtml
@{
    ViewData["Title"] = "AddNewBook";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model BookModel

<h1>AddNewBook</h1>

<h2>Hello from form view</h2>

<div class="container">
    <h3 class="display-4">Add New Book </h3>
    <hr />
    @if(ViewBag.IsSuccess)
    { 
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Congratualtions</strong> You Added A new book successfully.<br/>
    Click<a asp-controller="book" asp-action="Getbook" asp-route-id="@ViewBag.BookId">here</a> to view details;
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
    }
    
    <div class="row">
        <div class="col-md-12">
            <form method="post" asp-action="AddNewBook" asp-controller="Book">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="LanguageId"></label>
                    <select asp-for="LanguageId" class="form-control" asp-items="new SelectList(ViewBag.Lang)">
                        <option value="">Please Select language</option>

                    </select>
                    <span asp-validation-for="LanguageId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Author"></label>
                    <input asp-for="Author" class="form-control" />
                    <span asp-validation-for="Author" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TotalPages"></label>
                    <input asp-for="TotalPages" class="form-control" />
                    <span asp-validation-for="TotalPages" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description"></label>

                    <textarea asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Add Book" class="btn btn-primary" />
                </div>

            </form>
        </div>
    </div>
</div>

WebgentleBookStore/Views/Book/GetAllBooks.cshtml
@model IEnumerable<BookModel>

@*@model IEnumerable<WebgentleBookStore.Models.BookModel>*@
@{
    //ViewData["Title"] = "GetAllBooks";

    var bookViewData = ViewData["Book"] as BookModel;
}
@*@{
    var parameter = new Dictionary<string, string>()
{
        {"name","nisith" },
        { "company", "webgwntle"},
        {"appName","bookStore" }
    };
}
 asp-all-route-data="@parameter"*@

<div class="container">
    <h3 class="display-4">All Books</h3>
    @*<h2>@bookViewData.Language</h2>*@
    <div class="row">
        @foreach (var book in Model)
        {
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <svg class="bd-placeholder card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" />
                    <div class="card-body">
                        <h3 class="card-title">@book.Title</h3>
                        <p class="card-text">@book.Description</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a asp-controller="Book" asp-action="Getbook" asp-route-id="@book.Id" asp-route-bookName="@book.Title" class="btn btn-sm btn-outline-secondary">View Details</a>
                            </div>
                            <small class="text-muted">@book.Author</small>
                        </div>

                    </div>
                </div>
            </div>

        }

    </div>
</div>

WebgentleBookStore/Views/Book/GetBook.cshtml
@*@model WebgentleBookStore.Models.BookModel;*@

@{
    ViewData["Title"] = "GetBook ";
}


<div class="container">
    <h3 class="display-4">Book Details</h3>
    <div class="row">
        <div class="col-md-6">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">

                        <img src="~/images/splash.2.jpg" class="d-block w-100" asp-append-version="true" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="~/images/splash.jpg" class="d-block w-100" asp-append-version="true" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="~/images/splash4.jpg" class="d-block w-100" asp-append-version="true" alt="...">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <h1>@Model.Title</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <span class="label label-primary">By: </span>
                    <span class="monospaced">@Model.Author</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <p class="description">
                        @Model.Description
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <button class="btn btn-outline-primary">
                        Read Now
                    </button>
                </div>
            </div>
            <hr />
            <ul class="list-group">
                <li class="list-group-item"><span class="font-weight-bold">Category -</span> @Model.Category </li>
                <li class="list-group-item"><span class="font-weight-bold">Total Pages -</span>   @Model.TotalPages </li>
                <li class="list-group-item"><span class="font-weight-bold">Language -</span>@Model.LanguageId </li>
            </ul>



        </div>
    </div>
</div>
<hr />
<div class="py-5 bg-light" id="similarBooks">
    <div class="container">
        <h3 class="h3">Similar Books</h3>
        <div class="row">
            @for (int i = 0; i <= 5; i++)
            {
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <svg class="bd-placeholder card-img-top" width="100%" height="225" xmlns="https://www.w3.org/2000/svg" preserveAspectRatio="" />
                        <div class="card-body">
                            <h3 class="card-title">book.Title</h3>
                            <p class="card-text">book.Description</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="#" class="btn btn-sm btn-outline-secondary">Views Details</a>
                                </div>
                                <small class="text-muted">book.Author</small>
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>

WebgentleBookStore/Views/Car/AddCar.cshtml
@{
    ViewData["Title"] = "AddCar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model CarModel;

<h1>AddCar</h1>

<div class="container">
    @if (ViewBag.isSuccess)
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Congratualtions</strong> You Added A new car successfully.<br />
            Click<a asp-controller="book" asp-action="Getbook" asp-route-id="@ViewBag.BookId">here</a> to view details;
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
    <div class="row">
        <div class="col-md-12">
            <form method="post" asp-controller="Car" asp-action="AddCar">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Model"></label>
                    <input asp-for="Model" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Color"></label>
                    <input asp-for="Color" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Price"></label>
                    <input asp-for="Price" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Millage"></label>
                    <input asp-for="Millage" class="form-control" />
                </div>
                <input type="submit" value="submit" class="btn btn-danger" />
            </form>
        </div>
    </div>
</div>

WebgentleBookStore/Views/Home/AboutUs.cshtml
@*@{
    ViewData["Title"] = "AboutUs";
}*@

<h2>About Us</h2>

WebgentleBookStore/Views/Home/ContactUs.cshtml
@*@{
    ViewData["Title"] = "ContactUs";
}*@

<h1>ContactUs</h1>

WebgentleBookStore/Views/Home/Index.cshtml
@*@{ 
    Layout = null;
}*@
@*<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/Site.css" rel="stylesheet" />
    <title>Index</title>
</head>
<body class="container">*@
@{ 
    dynamic data = ViewBag.Data;
    var newData = ViewData["data"] as BookModel;
    //ViewData["Title"] = "Home";
}
<section class="jumbotron text-center">
    <div class="container">
        <h1>Welcome to Book store</h1>
        <h2>@newData.Author</h2>
        <h2>@newData.Language</h2>
        <h2>@ViewData["CustomProperty"]</h2>

        <environment names="Development">
            <h3>Development</h3>
        </environment>

        <environment names="Production">
            <h3>Production</h3>
        </environment>
        @*<p class="lead text-muted">
            lorem23 slsllllllllllllllllllllllllll
            <h2 class="h1">Welcome</h2>
            <h6 class="display-4">Welcome home danny</h6>
            <img src="~/images/splash4.jpg" />
            <input type="button" value="click me aslo" class="btn btn-success" />
            <img src="~/MyStaticFiles/splash3.jpg" />
            @Html.Label("FirstName", "FirstName:", new { @class = "caption" })
        </p>*@
        <p>
            <a href="#" class="btn btn-primary my-2">Search Books</a>
        </p>
    </div>


</section>

<div class="py-5 bg-light">
    <div class="container">
        <h3>Top Books</h3>
        <div class="row">
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <svg class="bd-placeholder card-img-top" width="100%" height="225" xmlns="http://www.w3.org/200"/>
                <div class="card-body">
                    <p class="card-text">This is section will be used</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="#" class="btn btn-sm btn-outline-secondary">View Details</a>
                        </div>
                    <small class="text-muted">Author Name</small>
                    </div>

                </div>
                         </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <svg class="bd-placeholder card-img-top" width="100%" height="225" xmlns="http://www.w3.org/200" />
                    <div class="card-body">
                        <p class="card-text">This is section will be used</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="#" class="btn btn-sm btn-outline-secondary">View Details</a>
                            </div>
                            <small class="text-muted">Author Name</small>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <svg class="bd-placeholder card-img-top" width="100%" height="225" xmlns="http://www.w3.org/200" />
                    <div class="card-body">
                        <p class="card-text">This is section will be used</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="#" class="btn btn-sm btn-outline-secondary">View Details</a>
                            </div>
                            <small class="text-muted">Author Name</small>
                        </div>

                    </div>
                </div> 
            </div>
        </div>
    </div>
</div>

 
@*including thr jquery link is not needed herer because it has been included in layout
<script src="~/lib/jquery/jquery.js"></script>*@
@section scripts{ 

    <script>
        $(document).ready(function () {
            //alert("Page loaded");
        });
    </script>
}

WebgentleBookStore/Views/Shared/ContactUs.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ContactUs</title>
</head>
<body>
    <h2>Hello from contact us</h2>
</body>
</html>

WebgentleBookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <environment include="Development">
        <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    </environment>
   
    @*<link href="~/css/Site.css" rel="stylesheet" />*@
    <title>@ViewData["Title"] |
    Book Store Application</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggler-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" href="/">
                    <img src="~/images/splash4.jpg" width="30" height="30" asp-append-version="true" />
                    Book Store
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="btn btn-outline-primary">Login</a>
                            <a class="btn btn-primary">Register</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Aboutus">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="contactus">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Book" asp-action="Getallbooks">All Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Book" asp-action="addnewbook">New Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Car" asp-action="addcar">New Car</a>
                        </li>
                    </ul>
                </div>
            </div>

        </nav>
    </header>
    <main role="main">
        @RenderBody()
    </main>
    <footer class="border-top footer text-muted text-center">
        <div class="container">
            Copyright &copy; Book Store  @DateTime.Now.Year
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/jquery.js"></script>
    </environment>
    <environment exclude="Develpoment">
        <script src="~/lib/jquery/jquery.min.js"></script>
    </environment>
  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    @RenderSection("scripts", required: false);
</body>
</html>